#!/bin/sh
# LODEL - Logiciel d'Édition ÉLectronique.
# @license GPL 2 (http://www.gnu.org/licenses/gpl.html) See COPYING file
# @authors See COPYRIGHT file

# script de creation de l'archive lodel pour diffusion
# a executer dans le repertoire parent d'une copie de travail du depot
# le repertoire contenant la copie de travail doit s'appeler lodel

if [ $# -lt 1 ]
then
  echo " usage $0 <version>"
  exit
fi

# nom du fichier genere
FILE="lodel-$1"


# verifie existence des repertoires
if [ -d lodel/lodel -a -d lodel/lodeladmin -a -d lodel/share ]; then
	# renomme les repertoires du depot svn pour contenir le numero de version
	mv lodel/lodel lodel/lodel
	mv lodel/lodeladmin lodel/lodeladmin
	mv lodel/share lodel/share
else
	echo " Tous les repertoires de Lodel ne sont pas presents "
	exit
fi

# tar.gz
tar czf $FILE.tar.gz lodel
if [ $? -ne 0 ]
then
  exit 1
fi
echo "fichier $FILE.tar.gz cree";

# zip
cd lodel
zip -rq ../$FILE.zip *
if [ $? -ne 0 ]
then
  exit 1
fi
echo "fichier $FILE.zip cree";
cd ../
ls -altr  $FILE*
