#!/bin/sh

# tar le contenu du repertoire lodel pour le transfert sur w2

FILE=/www-bin/revues/import/lodel.tar.gz

echo "creer le fichier $FILE";

find lodel \
	-path '*/CACHE/*' \
	-o -path '*/r2r/*' \
	-o -path '*/upload/*' \
	-o -name '*~' \
	-o -name '*.tmp' \
	-o -name '#*#' \
	-o -name '*.old' \
	-o -name 'OLD*' | tar --dereference -czf $FILE --exclude-from - lodel

ls -l  $FILE





