#!/bin/sh
# LODEL - Logiciel d'Édition ÉLectronique.
# @license    GPL 2 (http://www.gnu.org/licenses/gpl.html) See COPYING file
# @authors    See COPYRIGHT file

# tar le contenu du repertoire de la revue en argument pour le transfert sur w2

FILE=/www-bin/revues/import/revue-$1.tar.gz

echo "creer le fichier $FILE";

find $1 \
	-o -path '*/upload/*' \
	-o -path '*/docannexe/*' \
	-o -path '*/lodel/txt/*' \
	-o -path '*/lodel/rtf/*' \
	-o -name '*~' \
	-o -name '*.tmp' \
	-o -name '#*#' \
	-o -name '*.old' \
	-o -name 'OLD*' | tar --dereference -czf $FILE --exclude-from - $1

ls -l  $FILE





