#!/bin/bash
# reinitialisation des droits sur les fichiers et repertoires d'un revue
# Luc Santeramo/300103

if [ $# -ne 1 ]
then
  echo " usage $0 <repertoire de la revue> "
  exit
fi

LODEL="$1"

APACHEWRDIR="lodel/txt lodel/rtf docannexe lodel/admin/upload"
APACHECACHEWRDIR="CACHE lodel/edition/CACHE lodel/admin/CACHE"

USERWRFILES="tpl images styles_revue.css robots.txt"

HTACCESSDIR="CACHE tpl lodel/txt lodel/rtf lodel/edition/CACHE lodel/admin/CACHE lodel/admin/tpl lodel/edition/tpl"

HTACCESSCONTENT="deny from all"

# mise a jour des droits sur les rep et les fichiers 
# accessible en ecriture par apache

echo " "
echo "Changement des droits de la revue $1 :"

for rep in $APACHEWRDIR
do
  echo "  $LODEL/$rep"
  chmod 770 $LODEL/$rep
  echo "  Done."
  echo "  fichiers contenus dans $LODEL/$rep"
  chmod 660 $LODEL/$rep/*
  echo "  Done."
done

# mise a jour des droits sur les rep et fichiers
# accessible en ecriture par l'utilisateur

echo "  $LODEL"
chmod g+w $LODEL
echo "  Done."

for files in $USERWRFILES
do
  echo "  $files"
  chmod -R g+w $LODEL/$files
  echo "  Done."
done

# mise a jour des droits sur les rep de cache 
# accessible en ecriture par apache 
# nettoyage des repertoires de cache
for rep in $APACHECACHEWRDIR
do
  echo "  $LODEL/$rep"
  chmod 770 $LODEL/$rep
  rm -rf $LODEL/$rep/*
  echo "  Done."
done

# verification de la presence des .htaccess
echo " "
echo "Verification de la presence des .htaccess :"
for rep in $HTACCESSDIR
do
  if [ ! -e "$LODEL/$rep/.htaccess" ]
  then
    echo "$HTACCESSCONTENT" > "$LODEL/$rep/.htaccess"
    echo "  $LODEL/$rep/.htaccess absent"
    echo "  Cree."
  else
    echo "  $LODEL/$rep/.htaccess present"
  fi
  echo "  Changement des permissions sur le fichier $LODEL/$rep/.htaccess"
  chmod 644 $LODEL/$rep/.htaccess
  ls -al $LODEL/$rep/.htaccess
  echo "  Ok."
done
