#!/bin/bash -vx
#
#  LODEL - Logiciel d'Edition ELectronique.
#
#  Copyright (c) 2001-2002, Ghislain Picard, Marin Dacos
#  Copyright (c) 2003, Ghislain Picard, Marin Dacos, Luc Santeramo, Nicolas Nutten, Anne Gentil-Beccot
#
#  Home page: http://www.lodel.org
#
#  E-Mail: lodel@lodel.org
#
#                            All Rights Reserved
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

# vide les repertoires de cache de lodel et restaure les droits sur les fichiers/rep

if [ $# -ne 1 ]
then
  echo " usage $0 <repertoire racine de lodel> "
  exit
fi


LODEL="$1"

APACHECACHEWRDIR="lodel/admin/CACHE lodel/CACHE CACHE lodel/admin/upload"

HTACCESSDIR="lodel/admin/CACHE lodel/admin/tpl lodel/scripts lodel/r2r lodel/CACHE lodel/revue lodel/tpl lodel/install"

HTACCESSCONTENT="deny from all"

###

# mise a jour des droits sur les rep de cache
# accessible en ecriture par apache
# nettoyage des repertoires de cache
echo " "
echo "Verification des repertoires CACHE"
for rep in $APACHECACHEWRDIR
do
  echo "  $LODEL/$rep"
  chmod 770 $LODEL/$rep
  find $LODEL/$rep -not -name ".htaccess" -not -path "*/CVS*" -type f -exec rm -rf {} \;
  echo "  Done."
done

echo " "
echo "Verification de la presence des .htaccess :"
for rep in $HTACCESSDIR
do
  if [ ! -e "$LODEL/$rep/.htaccess" ]
  then
    echo "$HTACCESSCONTENT" > "$LODEL/$rep/.htaccess"
    echo "  $LODEL/$rep/.htaccess absent"
    echo "  Cree."
  else
    echo "  $LODEL/$rep/.htaccess present"
  fi
done
