#!/usr/bin/perl
###########################################################################
#
#      wrapper version 0.1 Fevrier 1999
#
#      Copyright (C) 1999, Ghislain Picard
#
###########################################################################
#
# Ce script peut etre diffuse et modifie librement. Il est distribue
# dans le but d'etre utile, mais SANS GARANTIE.
#
###########################################################################
#	wrapper [indexonly]
#
###########################################################################

### TPL Nom de la base de donnee
$dbname="r2r";
### TEND

$url_base="html";
###########################################################################

$arg=shift;
  &init;
  &parse0;			# decoupe les fichiers
  &parse1;			# construit la db et une premiere version des fichiers html

print "\nbye :-)\n\n";


sub init {
  print "initialisation des repertoire\n";
  
  
  opendir (DIRH,"./txt/");
  @dir=readdir (DIRH);
  closedir (DIRH);
}


sub parse0 {
  
  print "\nDecoupage: decoupage des fichier compte-rendu et notes\n\n";
  
  foreach $dirname (@dir) {
    if ($dirname=~/^\d+-\d+$/ && (!$arg || $dirname eq $arg)) {
      ## cree le rep dans tmp si necessaire

      `/bin/mkdir tmptxt` unless -e "tmptxt";
      `/bin/mkdir tmptxt/$dirname` unless -e "tmptxt/$dirname";
      `/bin/rm tmptxt/$dirname/*`;
      `/bin/cp txt/$dirname/* tmptxt/$dirname`;
      `/bin/mkdir html/$dirname` unless -e "html/$dirname";

      print "****************** $dirname ******************\n\n";
      opendir (SDIRH,"tmptxt/$dirname");
      @file=sort(readdir (SDIRH));
      closedir (SDIRH);
      
      foreach $filename (@file) {
	if ($filename=~/cpte-rendu.*\.html$/ || $filename=~/notes.*\.html$/ || $filename=~/chroniques.*\.html$/) {
	  print "############### $filename ####################\n";
	  (!system "./decoupe tmptxt/$dirname/$filename") || die "erreur dans decoupe $filename";					
	}
      }
    }
  }
}


sub parse1 {
  print "\nPremiere passe: creation des .html et insertion dans la la base de donnee\n\n";

  foreach $dirname (@dir) {
    if ($dirname=~/^\d+-\d+$/ && (!$arg || $dirname eq $arg)) {
      print "****************** $dirname ******************\n\n";
      opendir (SDIRH,"tmptxt/$dirname");
      @file=sort(readdir (SDIRH));
      closedir (SDIRH);

      foreach $filename (@file) {
	if ($filename=~/(.*)\.txt\.html$/) {
	  print "############### $filename ####################\n";
	  (!system "./wordcleaner tmptxt/$dirname/$filename") || die "erreur lors de l'execution de ./wordcleaner tmptxt/$dirname/$filename";
	  (!system "./peupledb $dbname tmptxt/$dirname/$1.txt.cl $dirname/$1.html $url_base/$dirname/$1.html") || die "erreur lors de l'execution de peuple\n";
	}
      }
    }
  }
}

