<?php

function isvalidfield($nom) 
{return preg_match("/^[a-zA-Z0-9]+$/",$nom);}


function isvalidstyle($nom)
{ return preg_match("/^[a-zA-Z0-9]+$/",$nom); }


// apres l'ajout d'un type, il faut mettre a jour le Schema XML

$GLOBALS[typechamps]=array("tinytext"=>"Texte court",
			   "text"=>"Texte",
			   "mltext"=>"Texte multilingue",
			   "image"=>"Image",
			   "fichier"=>"Fichier",
			   "url"=>"URL",
			   "date"=>"Date",
			   "datetime"=>"Date et Heure",
			   "time"=>"Heure",
			   "int"=>"Nombre entier",
			   "boolean"=>"Bool&eacute;en",
			   "number"=>"Nombre &agrave virgule",
			   "lang"=>"Langue",
			   "longtext"=>"Texte long",
			   );

$GLOBALS[sqltype]=array("tinytext"=>"tinytext",
			"text"=>"text",
			"mltext"=>"text",
			"image"=>"tinytext",
			"fichier"=>"tinytext",
			"url"=>"tinytext",
			"date"=>"date",
			"datetime"=>"datetime",
			"time"=>"time",
			"int"=>"int",
			"boolean"=>"tinyint",
			"number"=>"double precision",
			"lang"=>"char(2)",
			"longtext"=>"longtext",
			);

# fields for whom the strip_tags is applied automatically.

$GLOBALS[type_autostriptags]=array("image",
			      "fichier",
			      "url",
			      "date",
			      "datetime",
			      "time",
			      "int",
			      "boolean",
			      "number",
			      "lang",
			      );


// le style doit etre parfaitement valide
function decode_mlstyle($style)

{
  $stylesarr=preg_split("/[\n,:]/",$style);
  if (!$stylesarr) return array();
  $count=count($stylesarr);
  for($i=0; $i<$count; $i+=2) {
    $k=trim($stylesarr[$i+1]);
    $stylesassoc[$k]=trim($stylesarr[$i]);
  }
  return $stylesassoc;
}


// le style doit etre parfaitement valide
function isvalidmlstyle($style)

{
  $stylesarr=preg_split("/([\n,:])/",$style,-1,PREG_SPLIT_DELIM_CAPTURE);
  if (!$stylesarr) return TRUE;
  $count=count($stylesarr);
  for($i=0; $i<$count; $i+=4) {
    if (!isvalidstyle(trim($stylesarr[$i]))) return FALSE; // le style 
    if ($stylesarr[$i+1]!=":") return FALSE; // le separateur
    if (!preg_match("/^\s*[a-z]{2}\s*$/",$stylesarr[$i+2])) return FALSE; // la langue
    if ($stylesarr[$i+3]==":") return FALSE; // les autres separateurs

    $k=trim($stylesarr[$i+1]);
    $stylesassoc[$k]=trim($stylesarr[$i+1]);
  }
  return TRUE;
}


function reservedword($nom) {
$reserved_words = array("ADD",
	"ALL",
	"ALTER",
	"ANALYZE",
	"AND",
	"AS",
	"ASC",
	"ASENSITIVE",
	"AUTO_INCREMENT",
	"BDB",
	"BEFORE",
	"BERKELEYDB",
	"BETWEEN",
	"BIGINT",
	"BINARY",
	"BLOB",
	"BOTH",
	"BTREE",
	"BY",
	"CALL",
	"CASCADE",
	"CASE",
	"CHANGE",
	"CHAR",
	"CHARACTER",
	"CHECK",
	"CLASSE",
	"COLLATE",
	"COLUMN",
	"COLUMNS",
	"CONNECTION",
	"CONSTRAINT",
	"CREATE",
	"CROSS",
	"CURRENT_DATE",
	"CURRENT_TIME",
	"CURRENT_TIMESTAMP",
	"CURSOR",
	"DATABASE",
	"DATABASES",
	"DAY_HOUR",
	"DAY_MICROSECOND",
	"DAY_MINUTE",
	"DAY_SECOND",
	"DEC",
	"DECIMAL",
	"DECLARE",
	"DEFAULT",
	"DELAYED",
	"DELETE",
	"DESC",
	"DESCRIBE",
	"DISTINCT",
	"DISTINCTROW",
	"DIV",
	"DOUBLE",
	"DROP",
	"ELSE",
	"ELSEIF",
	"ENCLOSED",
	"ERRORS",
	"ESCAPED",
	"EXISTS",
	"EXPLAIN",
	"FALSE",
	"FIELDS",
	"FLOAT",
	"FOR",
	"FORCE",
	"FOREIGN",
	"FROM",
	"FULLTEXT",
	"GRANT",
	"GROUP",
	"GROUPE",
	"HASH",
	"HAVING",
	"HIGH_PRIORITY",
	"HOUR_MICROSECOND",
	"HOUR_MINUTE",
	"HOUR_SECOND",
	"ID",
	"IDENTITE",
	"IDPARENT",
	"IDTYPE",
	"IDUSER",
	"IF",
	"IGNORE",
	"IN",
	"INDEX",
	"INFILE",
	"INNER",
	"INNODB",
	"INOUT",
	"INSENSITIVE",
	"INSERT",
	"INT",
	"INTEGER",
	"INTERVAL",
	"INTO",
	"IO_THREAD",
	"IS",
	"ITERATE",
	"JOIN",
	"KEY",
	"KEYS",
	"KILL",
	"LEADING",
	"LEAVE",
	"LEFT",
	"LIKE",
	"LIMIT",
	"LINES",
	"LOAD",
	"LOCALTIME",
	"LOCALTIMESTAMP",
	"LOCK",
	"LONG",
	"LONGBLOB",
	"LONGTEXT",
	"LOOP",
	"LOW_PRIORITY",
	"MAJ",
	"MASTER_SERVER_ID",
	"MATCH",
	"MEDIUMBLOB",
	"MEDIUMINT",
	"MEDIUMTEXT",
	"MIDDLEINT",
	"MINUTE_MICROSECOND",
	"MINUTE_SECOND",
	"MOD",
	"MRG_MYISAM",
	"NATURAL",
	"NOM",
	"NOT",
	"NO_WRITE_TO_BINLOG",
	"NULL",
	"NUMERIC",
	"ON",
	"OPTIMIZE",
	"OPTION",
	"OPTIONALLY",
	"OR",
	"ORDER",
	"ORDRE",
	"OUT",
	"OUTER",
	"OUTFILE",
	"PRECISION",
	"PRIMARY",
	"PRIVILEGES",
	"PROCEDURE",
	"PURGE",
	"READ",
	"REAL",
	"REFERENCES",
	"REGEXP",
	"RENAME",
	"REPEAT",
	"REPLACE",
	"REQUIRE",
	"RESTRICT",
	"RETURN",
	"RETURNS",
	"REVOKE",
	"RIGHT",
	"RLIKE",
	"RTREE",
	"SECOND_MICROSECOND",
	"SELECT",
	"SENSITIVE",
	"SEPARATOR",
	"SET",
	"SHOW",
	"SMALLINT",
	"SOME",
	"SONAME",
	"SPATIAL",
	"SPECIFIC",
	"SQL_BIG_RESULT",
	"SQL_CALC_FOUND_ROWS",
	"SQL_SMALL_RESULT",
	"SSL",
	"STARTING",
	"STATUT",
	"STRAIGHT_JOIN",
	"STRIPED",
	"TABLE",
	"TABLES",
	"TERMINATED",
	"THEN",
	"TINYBLOB",
	"TINYINT",
	"TINYTEXT",
	"TO",
	"TPL",
	"TPLCREATION",
	"TPLEDITION",
	"TRAILING",
	"TRUE",
	"TYPE",
	"TYPES",
	"UNION",
	"UNIQUE",
	"UNLOCK",
	"UNSIGNED",
	"UNTIL",
	"UPDATE",
	"USAGE",
	"USE",
	"USER_RESOURCES",
	"USING",
	"UTC_DATE",
	"UTC_TIME",
	"UTC_TIMESTAMP",
	"VALUES",
	"VARBINARY",
	"VARCHAR",
	"VARCHARACTER",
	"VARYING",
	"WARNINGS",
	"WHEN",
	"WHERE",
	"WHILE",
	"WITH",
	"WRITE",
	"XOR",
	"YEAR_MONTH",
	"ZEROFILL");
	return (in_array (strtoupper($nom), $reserved_words));
}



?>
