#!/usr/bin/perl
# LODEL - Logiciel d'Édition ÉLectronique.
# @license GPL 2 (http://www.gnu.org/licenses/gpl.html) See COPYING file
# @authors See COPYRIGHT file

use strict;
use XML::Handler::YAWriter;
use XML::Driver::HTML;
use IO::File;

my $ya = new XML::Handler::YAWriter(
    'Output' => new IO::File ( ">-" ),
    'Encoding' => "ISO-8859-1",
    'Pretty' => {
	'NoComments'=>0,
	'AddHiddenNewline'=>0,
	'AddHiddenAttrTab'=>0,
	'CatchEmptyElement'=>0,
	}
    );

  $ya->{'Escape'} = {
		    '&'  => '&amp;',
		    '<'  => '&lt;',
		    '>'  => '&gt;',
		    '"'  => '&quot;'};

my $html = new XML::Driver::HTML(
    'Handler' => $ya,
    'Source' => {
    	'ByteStream' => new IO::File ( "<-" ),
	}
    );

$html->parse();


