#!/usr/bin/perl
#
#  LODEL - Logiciel d'Edition ELectronique.
#
#  Copyright (c) 2001-2002, Ghislain Picard, Marin Dacos
#  Copyright (c) 2003-2004, Ghislain Picard, Marin Dacos, Luc Santeramo, Nicolas Nutten, Anne Gentil-Beccot
#
#  Home page: http://www.lodel.org
#
#  E-Mail: lodel@lodel.org
#
#                            All Rights Reserved
#
#     This program is free software; you can redistribute it and/or modify
#     it under the terms of the GNU General Public License as published by
#     the Free Software Foundation; either version 2 of the License, or
#     (at your option) any later version.
#
#     This program is distributed in the hope that it will be useful,
#     but WITHOUT ANY WARRANTY; without even the implied warranty of
#     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#     GNU General Public License for more details.
#
#     You should have received a copy of the GNU General Public License
#     along with this program; if not, write to the Free Software
#     Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.

#
# Copyright (c) 2001 Michael Koehne <kraehe@copyleft.de>
#
# XML::Filter::HTML is free software. You can redistribute and/or modify
# this copy under terms of the GNU General Public License.


use strict;
use XML::Handler::YAWriter;
use XML::Driver::HTML;
use IO::File;

my $ya = new XML::Handler::YAWriter(
    'Output' => new IO::File ( ">-" ),
    'Encoding' => "ISO-8859-1",
    'Pretty' => {
	'NoComments'=>0,
	'AddHiddenNewline'=>0,
	'AddHiddenAttrTab'=>0,
	'CatchEmptyElement'=>0,
	}
    );

  $ya->{'Escape'} = {
		    '&'  => '&amp;',
		    '<'  => '&lt;',
		    '>'  => '&gt;',
		    '"'  => '&quot;'};

my $html = new XML::Driver::HTML(
    'Handler' => $ya,
    'Source' => {
    	'ByteStream' => new IO::File ( "<-" ),
	}
    );

$html->parse();


