#!/usr/bin/perl
#
# Copyright (c) 2001 Michael Koehne <kraehe@copyleft.de>
#
# XML::Filter::HTML is free software. You can redistribute and/or modify
# this copy under terms of the GNU General Public License.


use strict;
use XML::Handler::YAWriter;
use XML::Driver::HTML;
use IO::File;

my $ya = new XML::Handler::YAWriter(
    'Output' => new IO::File ( ">-" ),
    'Encoding' => "ISO-8859-1",
    'Pretty' => {
	'NoComments'=>0,
	'AddHiddenNewline'=>0,
	'AddHiddenAttrTab'=>0,
	'CatchEmptyElement'=>0,
	}
    );

  $ya->{'Escape'} = {
		    '&'  => '&amp;',
		    '<'  => '&lt;',
		    '>'  => '&gt;',
		    '"'  => '&quot;'};

my $html = new XML::Driver::HTML(
    'Handler' => $ya,
    'Source' => {
    	'ByteStream' => new IO::File ( "<-" ),
	}
    );

$html->parse();


